### ISSUE TITLE
記事にコメントつけられるようにする

### ISSUE THREAD

**Issue by ryutah** [dokurin/kontrex#10]
## TODO

- [Disqus](https://disqus.com/)のアカウント作る
- コメント機能追加

---

refs
- https://gohugo.io/content-management/comments/
- https://github.com/panr/hugo-theme-hello-friend#add-ons

**Comment by ryutah** [comment]
アカウントをどうするかが問題。
Google Groupでも作るか？

**Comment by ryutah** [comment]
(別にコメントとかいらんか)

**Comment by yoshioH** [comment]
下手に作っても手間だし、GoogleのGroupで間に合うならそれにしよう。

**Comment by yoshioH** [comment]
コメント機能はいらなくない？
HUGO単体で対応できればあってもいいと思うけど、JavaScriptとかでうまい具合にやる感じ？

**Comment by ryutah** [comment]
https://michimani.net/post/blog-install-disqus-to-hugo/

↑こんな感じ。
Disqusっていうコメントサービス使ってどーのこーの。まあ正直、別にいらんかって思っとりますー。

**Comment by yoshioH** [comment]
なるほどねー。
あとから対応可能ぽいし、優先順位下げて熟成させておこう。
