### ISSUE TITLE
Hugoローカル環境用Dockerイメージの作成

### ISSUE THREAD

**Issue by ryutah** [dokurin/kontrex#5]
## TODO

- 次のことができるDockerイメージを作成
  - ローカルサーバ起動
  - 静的ファイルのビルド
- DockerHubにPush

**Comment by ryutah** [comment]
#3 が終わってから着手。

**Comment by ryutah** [comment]
とりあえず、ローカルで記事見れる様になったし着手できそうかな？

**Comment by yoshioH** [comment]
あざますー。着手します。

**Comment by yoshioH** [comment]
公式のDockerイメージ使っている人少ないけどなんでだろ？
↓（やってみる）
あ、（察し）

**Comment by yoshioH** [comment]
`docker-compose up` すれば動きますー。
